//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_SubUserRole
    {
        public int SubRoleId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Components { get; set; }
        public string Operators { get; set; }
        public string Action { get; set; }
        public string Clause { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MakerWorkStationId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SMS_UserRole SMS_UserRole { get; set; }
    }
}
