//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_Menu
    {
        public int MenuId { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> ChildId { get; set; }
        public string MenuName { get; set; }
        public string Action { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MakerWorkStationId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public List<SMS_Menu> MenuList { get; set; } 
    }
}
