//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMS_User
    {
        public int RowId { get; set; }
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> DeptCode { get; set; }
        public Nullable<int> EmpCode { get; set; }
        public Nullable<int> LoginLimit { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<bool> UserChangePassword { get; set; }
        public Nullable<int> FirstLoginId { get; set; }
        public Nullable<System.DateTime> LoginTImeFrom { get; set; }
        public Nullable<System.DateTime> LoginTimeTo { get; set; }
        public Nullable<int> LogedNo { get; set; }
        public string Picture { get; set; }
        public string MakerWorkStationId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual SMS_Group SMS_Group { get; set; }
     
    }
}
