//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities : DbContext
    {
        public SMSEntities()
            : base("name=SMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SMS_Group> SMS_Group { get; set; }
        public virtual DbSet<SMS_Menu> SMS_Menu { get; set; }
        public virtual DbSet<SMS_User> SMS_User { get; set; }
        public virtual DbSet<SMS_UserRole> SMS_UserRole { get; set; }
        public virtual DbSet<SMS_SubUserRole> SMS_SubUserRole { get; set; }
    }
}
